spring:
  application:
    name: customer-service
  r2dbc:
    url: r2dbc:h2:mem:///customerdb;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  admin:
    client:
      instance:
        service-base-url: http://localhost:9095
      name: customer-service

server:
  port: 8080

# JVM configuration for containerized environment
java:
  opts: >
    -XX:MaxRAMPercentage=75.0
    -XX:InitialRAMPercentage=50.0
    -XX:+UseContainerSupport 

logging:
  level:
    org.springframework.r2dbc: DEBUG
    com.example.customer_service: DEBUG