apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config
data:
  application.yml: |
    spring:
      r2dbc:
        url: r2dbc:h2:mem:///customerdb
        username: sa
        password: 
      data:
        web:
          pageable:
            default-page-size: 10
            max-page-size: 100
      jackson:
        property-naming-strategy: SNAKE_CASE

    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
      endpoint:
        health:
          probes:
            enabled: true 