apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: customer-service
      context: .
      docker:
        dockerfile: Dockerfile
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml 